config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),

]

urlpatterns += i18n_patterns(path("", include('home.urls')),
                             path('', include('uzer.urls')), )

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from .views import my_home_view, creat_post_view, post_detail_views
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path("", my_home_view, name='my_home'),
    path("create_post/", creat_post_view, name='create_post'),
    path('detail/<int:id>/', post_detail_views, name='detail')
]

uzer/urls.py
from django.urls import path
from .views import registration_views, login_views,logout_views

app_name = 'user'
urlpatterns = [
    path('registration/', registration_views, name='registration'),
    path('login/', login_views, name='login'),
    path('logout/', logout_views, name='logout'),
]

home/models.py
from django.db import models
from ckeditor.fields import RichTextField
from uzer.models import UzerModel


class CategoryModel(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class TagModel(models.Model):
    tag = models.CharField(max_length=100)

    def __str__(self):
        return self.tag

    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'


# Create your models here.
class PostModel(models.Model):
    title = models.CharField(max_length=225)
    body = RichTextField()
    img = models.ImageField(upload_to='posts/')
    create_add = models.DateTimeField(auto_now_add=True)
    # category = models.ForeignKey(CategoryModel, on_delete=models.RESTRICT)
    # tag = models.ManyToManyField(TagModel, related_name='posts')
    user = models.ForeignKey(UzerModel, on_delete=models.RESTRICT)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'

uzer/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class UzerModel(AbstractUser):
    img = models.ImageField(upload_to='uzers/')

# Create your models here.

home/forms.py
from django import forms
from ckeditor.fields import RichTextFormField
from django.utils.translation import gettext_lazy as _


class PostCreateForm(forms.Form):
    title = forms.CharField(max_length=100, label=_('title'), widget=forms.TextInput(attrs={
        'placeholder': _("Post title")
    }))

    body = RichTextFormField(label=_('Post body'))

    img = forms.ImageField(widget=forms.FileInput(), label=_('Post image'))

uzer/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import UzerModel
from django.utils.translation import gettext_lazy as _


class LoginForms(forms.Form):
    username = forms.CharField(max_length=25, label=_("Username"), min_length=3, widget=forms.TextInput(attrs={
        'placeholder': _('Username')
    }))
    password = forms.CharField(max_length=16, label=_("Password"), min_length=6, widget=forms.PasswordInput(attrs={
        'placeholder': _('Password')
    }))


class RegistrationForms(forms.Form):
    username = forms.CharField(max_length=100, label=_("Username"), min_length=3, widget=forms.TextInput(attrs={
        'placeholder': _('Username')
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Youremailname@gmail.com'
    }))
    first_name = forms.CharField(label=_("First name"), max_length=25)
    last_name = forms.CharField(label=_("Last name"), max_length=25)
    password = forms.CharField(label=_("Password"), max_length=16, min_length=6, widget=forms.PasswordInput)
    confirm_password = forms.CharField(label=_("Confirm password"), max_length=16, min_length=6,
                                       widget=forms.PasswordInput)

    def clean_confirm_password(self):
        if self.cleaned_data['password'] != self.cleaned_data['confirm_password']:
            raise ValidationError(_("The passwords are not thr some!"))
        else:
            return self.cleaned_data

    def clean_user(self):
        user = UzerModel.objects.get(username=self.cleaned_data['username'])
        if user:
            raise ValidationError(_("This username is busy"))
        else:
            return self.cleaned_data

home/views.py
from django.shortcuts import render, redirect
from .forms import PostCreateForm
from .models import PostModel
from hitcount.utils import get_hitcount_model
from hitcount.views import HitCountMixin


def post_detail_views(request, id):
    post = PostModel.objects.get(id=id)

    hit_count = get_hitcount_model().objects.get_for_object(post)
    # hits = hit_count.hits
    hit_count_response = HitCountMixin.hit_count(request, hit_count)

    return render(request, 'main/detail.html', context={
        'post_id': post,
        'hit_count_object': hit_count_response
    })


def my_home_view(request):
    posts = PostModel.objects.all()
    return render(request, 'main/home.html', context={
        'posts': posts
    })


# Create your views here.

def creat_post_view(request):
    form = PostCreateForm()
    if request.method == 'POST':
        form = PostCreateForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_psot = PostModel.objects.create(
                title=form.cleaned_data['title'],
                body=form.cleaned_data['body'],
                img=form.cleaned_data['img'],
                user=request.user
            )
            new_psot.save()
            return redirect('blog:my_home')
    return render(request, 'main/post_craet.html', context={
        'create_form': form
    })

uzer/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForms, LoginForms
from .models import UzerModel
from django.contrib.auth.hashers import make_password
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate, login, logout
from django.utils.translation import gettext_lazy as _

def logout_views(request):
    logout(request)
    return redirect('blog:my_home')


def login_views(request):
    form_login = LoginForms()
    if request.method == 'POST':
        form_login = LoginForms(data=request.POST)
        if form_login.is_valid():
            uzer = authenticate(username=form_login.cleaned_data['username'],
                                password=form_login.cleaned_data['password'])
            if uzer is not None:
                login(request, uzer)
                return redirect('blog:my_home')
            else:
                form_login.add_error("password", 'Parol yoki username xato!')
    return render(request, 'main/login.html', context={
        'login_views': form_login
    })


def registration_views(request):
    form = RegistrationForms()
    if request.method == 'POST':
        form = RegistrationForms(data=request.POST)
        if form.is_valid():
            user = UzerModel(
                username=form.cleaned_data['username'],
                email=form.cleaned_data['email'],
                last_name=form.cleaned_data['last_name'],
                first_name=form.cleaned_data['first_name'],
                password=make_password(form.cleaned_data['password'])

            )
            user.save()
            return redirect('user:login')
    return render(request, 'main/registration.html', context={
        'registration_form': form
    })
#
#
# def registration_views(request):
#     form = RegistrationForms()
#     if request.method == 'POST':
#         form = RegistrationForms(data=request.POST)
#         if form.is_valid():
#             user = UzerModel(
#                 username=form.cleaned_data['username'],
#                 email=form.cleaned_data['email'],
#                 first_name=form.cleaned_data['first_name'],
#                 last_name=form.cleaned_data['last_name'],
#                 password=make_password(form.cleaned_data['password'])
#             )
#             user.save()
#             return redirect('blog:my_home')
#         return render(request, 'main/registration.html', context={
#             'registration_form': form
#         })

templates/layauts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}">
    {#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"#}
    {#          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">#}
    {#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">#}
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'layauts/navbar.html' %}


<div class="container">
    <div class="row">
        {% block content %}

        {% endblock %}
    </div>
</div>

<script src="{% static 'bootstrap/js/bootstrap.bundle.js' %}"></script>
{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"#}
{#        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"#}
{#        crossorigin="anonymous"></script>#}
<script src="{% static 'main/js/main.js' %}"></script>
</body>
</html>

templates/layauts/navbar.html
{% load i18n %}

<nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd">
    <div class="container">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:my_home' %}">{% trans 'Home' %}</a>
                </li>

                {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:registration' %}">{% trans 'Registration' %}</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'user:login' %}">{% trans 'Login' %}</a>
                    </li>
                {% else %}
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'user:logout' %}">{% trans 'Logout' %}</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'blog:create_post' %}">{% trans 'Create Post' %}</a>
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="{% trans 'Search' %}" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">{% trans 'Search' %}</button>
            </form>

            <ul class="navbar-nav">
                {% get_current_language as lang %}
                {% get_available_languages as LANGUAGES %}

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        {{ lang }}
                    </a>
                    <ul class="dropdown-menu">
                        {% for language in LANGUAGES %}
                            <li><a class="dropdown-item {% if language.0 == lang %} bg-primary text-white {% endif %}"
                                   href="/{{ language.0 }}/{{ request.path|slice:'4:' }}">{{ language.1 }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/main/detail.html
{% extends 'layauts/base.html' %}
{% load hitcount_tags %}

{% block content %}
    <div class="col-8 offset-2 mt-3">
        <img src="{{ post_id.img.url }}" alt="{{ post_id.title }}" class="img-fluid" style="height: 350px">
        <h1>{{ post_id.title }}</h1>
        <p>{{ post_id.body|safe }}</p>
        <div class="d-flex justify-content-between" style="width: 525px">
            {% get_hit_count for post_id as hit_c %}
            <span>
                {{ post_id.create_add|timesince }}
            </span>
            <span class="bi bi-eye-fill">
                {{ hit_c }}
            </span>
        </div>
    </div>
{% endblock %}

templates/main/home.html
{% extends 'layauts/base.html' %}
{% load crispy_forms_filters %}
{% load hitcount_tags %}


{% block content %}
    {% for post in posts %}
        <div class="col-4 mt-3 ">
            <div class="card mb-3">
                <img src="{{ post.img.url }}" class="card-img-top" alt="{{ post.title }}" style="height: 250px">
                <div class="card-body">
                    {% get_hit_count for post as hit_c %}
                    <h5 class="card-title"><a href="{% url 'blog:detail' post.id %}" class="text-dark">{{ post.title|title }}</a></h5>
                    <p class="card-text">{{ post.body|safe|truncatewords:4 }}</p>
                    <p class="card-text d-flex justify-content-between"><small class="text-body-secondary">{{ post.create_add|timesince }} ago</small>
                        <span class="bi bi-eye-fill">
                        {{ hit_c }}
                    </span> </p>


                </div>
            </div>

        </div>
    {% endfor %}
{% endblock %}

templates/main/login.html
{% extends 'layauts/base.html' %}
{% load crispy_forms_filters i18n%}

{% block content %}
    <div class="col-6 offset-3 mt-5">
        <div class="card">
            <div class="card-header bg-dark text-white">
                {% trans 'Login' %}
            </div>
            <div class="card-body">
                <form action="{% url 'user:login' %}" method="post">
                    {% csrf_token %}
                    {{ login_views|crispy }}
                    <button class="btn btn-primary px-5 py-2">{% trans 'Save' %}</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/main/post_craet.html
{% extends 'layauts/base.html' %}
{% load crispy_forms_filters i18n %}

{% block content %}
    <div class="col-10 offset-1 mt-3">
        <div class="card">
            <div class="card-header bg-dark text-white">
                {% trans 'Create post' %}
            </div>
            <div class="card-body">
                <form action="{% url 'blog:create_post' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ create_form|crispy }}
                    {{ create_form.media }}
                    <button class="btn btn-primary px-5 py-2">{% trans 'Create' %}</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/main/registration.html
{% extends 'layauts/base.html' %}
{% load crispy_forms_filters %}
{% load i18n %}


{% block content %}
    <div class="col-6 offset-3 mt-5">
        <div class="card">
            <div class="card-header bg-dark text-white">
                {% trans 'Registration' %}
            </div>
            <div class="card-body">
                <form action="{% url 'user:registration' %}" method="post">
                    {% csrf_token %}
                    {{ registration_form|crispy }}
                    <button class="btn btn-primary px-5 py-2">{% trans 'Save' %}</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/main/user_profile.html
{% extends 'layauts/base.html' %}


{% block content %}

{% endblock %}